spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate:
      SQL: trace
      type.descriptor.sql.BasicBinder: trace

eureka:
  instance:
    hostname: demo
  client:
    register-with-eureka: false
    fetch-registry: false

hazelcast:
  address: ${HAZELCAST_ADDRESS:hazelcast:5701}
  group:
    name: ${HAZELCAST_GROUP:username}
    password: ${HAZELCAST_PASS:password}

first:
  baseUrl: http://localhost:9090
  username: username
  password: password

second:
  baseUrl: http://localhost:9091
  username: username
  password: password
