
server:
  port: 8090
info:
  app:
    description: "Service to manage customers"
management:
  server:
    port: 8088
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

eureka:
  instance:
    hostname: customer-service
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  threads:
    virtual:
      enabled: true

first:
  baseUrl: http://localhost:9090
  username: username
  password: password

second:
  baseUrl: http://localhost:9091
  username: username
  password: password